# Copyright (C) 2023-2024  Horimoto Yasuhiro <horimoto@clear-code.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.

name: Test
on:
  - push
  - pull_request
jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        raku-version:
          - "2023.08-01"
        image:
          - "images:ubuntu/24.04"
          - "images:ubuntu/22.04"
          - "images:debian/12"
          - "images:almalinux/8"
          - "images:almalinux/9"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install required packages for building Star Bundle
        run: |
          sudo apt update
          sudo apt install -y -V build-essential git libssl-dev
      - name: Build Star Bundle
        run: |
          mkdir rakudo
          pushd rakudo
          curl -LJO https://rakudo.org/latest/star/src
          tar -xzf rakudo-star-*.tar.gz
          mv rakudo-star-*/* .
          rm -rf rakudo-star-*
          ./bin/rstar install
          popd
      - name: Install Incus
        run: |
          sudo apt install -y -V incus
      - name: Allow egress network traffic flows for Incus
        # https://linuxcontainers.org/incus/docs/main/howto/network_bridge_firewalld/#prevent-connectivity-issues-with-incus-and-docker
        run: |
          sudo iptables -I DOCKER-USER -i incusbr0 -j ACCEPT
          sudo iptables -I DOCKER-USER -o incusbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      - name: Run tests
        run: |
          set -x
          sudo incus admin init --auto
          sudo incus launch ${{ matrix.image }} target
          ls -al $PWD
          sudo incus config device add target host disk source=$PWD path=/host
          sleep 10
      - name: Run tests
        run: |
          sudo incus exec target \
            -- \
            /host/t/setup.sh
            /host/t/run-tests.sh
      - name: Remove container
        run: |
          sudo incus stop target
          sudo incus delete target
